vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       user_images:
           uri_prefix: /image
           upload_destination: '%kernel.project_dir%/public/image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true